services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - db
    ports:
      - "6543:6543"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: ["npm","run","dev"]
    volumes:
      - ./frontend:/app          # mount kode dari host
      - /app/node_modules 
      
volumes:
  pgdata: