services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alfino123
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - db
    ports:
      - "6543:6543"

  frontend:
    build: ./frontend
    command: ["npm","run","dev"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

volumes:
  pgdata: