FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 6543
CMD [ "python", "-m", "pyramid.scripts.pserve", "development.ini", "--reload" ]